#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Byronlun

# Short bio or description (displayed in the header)
description: A Front End Fans

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: images/me.png


# Includes an icon in the footer for each username you enter
author: 'Byronlun Fang'

author-email: 'byronlunfang@gmail.com'

baseurl: '' 

url: http://byronlun.github.io/

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: byronlun
  instagram:
  linkedin:
  pinterest:
  rss: /feed.xml
  twitter: byronlunF
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

permalink: /posts/:year-:month-:day-:title.html

# paginate: 5
paginate_path: "blog/page:num/"

# # Jekyll 3 now only supports Kramdown for Markdown
# kramdown:
#   # Use GitHub flavored markdown, including triple backtick fenced code blocks
#   input: GFM
#   # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     # Use existing pygments syntax highlighting css
#     css_class: 'highlight'

markdown: kramdown
highlighter: rouge

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude: [Gemfile, Gemfile.lock, LICENSE, README.md, CNAME]
